on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push main branch
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: deploy frontend to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: '${{ secrets.SFTP_USERNAME }}'
          server: '${{ secrets.SERVER }}'
          port: '${{ secrets.SSH_PORT }}'
          local_path: './dist/*'
          remote_path: '/home/hfmexico/public_html/futuristic-minds-scanner.igeco.mx'
          sftp_only: true
          password: '${{ secrets.SFTP_PASSWORD }}'

      - name: deploy backend to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: '${{ secrets.SFTP_USERNAME }}'
          server: '${{ secrets.SERVER }}'
          port: '${{ secrets.SSH_PORT }}'
          local_path: './server'
          remote_path: '/home/hfmexico/public_html/futuristic-minds-scanner.igeco.mx'
          sftp_only: true
          password: '${{ secrets.SFTP_PASSWORD }}'
